name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3
      - name: "Install"
        run: npm install
      - name: "Deploy"
        run: CLOUDFLARE_API_TOKEN=${{ vars.CF_API_TOKEN }} npm run deploy
